language: node_js
node_js:
- 6.1.0

script:
- set -e # Exit on any error
- pushd ..
- git clone --branch v0.0.1 --depth 1 https://github.com/Caleydo/caleydo_web_container.git
- ln -s bundle_lib/ caleydo_web_container/plugins/
- pushd caleydo_web_container
- npm install -g grunt tsd
- bash manage.sh resolve_dev
- grunt --jenkins

sudo: false # container-based infrastructure for a faster build
