language: node_js
node_js:
- 0.12.7 # Referenced by Jenkins; Released 2015-07-09.
#- 6.1.0

script:
- set -e # Exit on any error
- pushd ..
-   git clone --branch v0.0.1 --depth 1 https://github.com/Caleydo/caleydo_web_container.git
-   pushd caleydo_web_container
-     pushd plugins
-       ln -s ../../bundle_lib/ .
-     popd
-     npm install
-     npm install -g grunt tsd
-     bash manage.sh resolve_dev
-     grunt --jenkins
-   popd
- popd
sudo: false # container-based infrastructure for a faster build
